source_repository_url: https://github.com/siman-man/sample_repo.git
target_repository_url: https://github.com/siman-man/sample_repo.git
source_branch: master
target_branch: japanese
source_lang: en
target_lang: ja
paths:
  doc/*.md: doc/ja
